# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Information_Gathering
  jobs:
  - job: Get_Info
    steps:
    - bash: echo 'Build number is '$(Build.BuildNumber)
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeploy
    steps:
    - bash: echo Dev Deploy Job 
    - bash: echo $PIPELINE_LEVEL
- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeploy
    steps:
    - bash: echo QA Deploy Job 
- stage: ProDeploy
  variables:
    environment: Dev
  dependsOn:
  - DevDeploy 
  - QADeploy

  jobs:
  - job: 
    steps:
    - bash: echo Production Deploy$(environment)




