

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: angularbackenddeployment 
spec: 
  selector: 
    matchLabels: 
      app: angularbackend
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: angularbackend
    spec: 
      containers: 
      - name: angularbackend
        image: anurag4516/backend:v1
        ports: 
        - containerPort: 8080 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: angularbackendservice 
spec: 
  selector: 
    app: angularbackend 
  ports: 
  - protocol: TCP 
    port: 8080 
    targetPort: 8080 
    nodePort: 32000 
  type: NodePort 
